version: '3'
services:
  database:
    container_name: database
    build: ./database
    ports:
      - "5432:5432"
  app:
    container_name: flask_app
    build: ./app
    ports:
      - "5000:5000"
    links:
      - database